name: FOSSA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fossa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install dependencies
        run: ./gradlew build

      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@09bcf127dc0ccb4b5a023f6f906728878e8610ba # v1.4.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          branch: ${{ github.ref_name }}

      - name: Run FOSSA tests
        uses: fossas/fossa-action@09bcf127dc0ccb4b5a023f6f906728878e8610ba # v1.4.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
